# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BLOG CLIENT CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Git Checkout
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Project
      run: npm install && npm run build
    - name: Deploy to aliyun server
      uses: easingthemes/ssh-deploy@v2.1.2
      env:
          SSH_PRIVATE_KEY: ${{ secrrets.ALIYUN_SERVER_ACCESS_TOKEN }}
          ARGS: "-avzr --delete"
          SOURCE: dist
          REMOTE_HOST: ${{ secrrets.ALIYUN_SERVER_HOST }}
          TARGET: "~/blog/client"
          driver: oss
          region: oss-cn-beijing

